version: "3.8"

services:
  pubsub-emulator:
    image: google/cloud-sdk:latest
    container_name: pubsub_emulator
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"
    environment:
      - CLOUDSDK_PYTHON=python3

  web:
    build: .
    container_name: registration_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - GCP_PROJECT=local-project
      - EMAIL_TOPIC=email-topic
    depends_on:
      - pubsub-emulator
    
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request, sys; \
resp=urllib.request.urlopen('http://127.0.0.1:8000/health'); \
sys.exit(0) if resp.getcode()==200 else sys.exit(1)\""]
      interval: 15s
      timeout: 5s
      retries: 5

  worker:
    build: .
    container_name: registration_worker
    restart: always
    command: ["python", "worker/worker.py"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - GCP_PROJECT=local-project
      - EMAIL_TOPIC=email-topic
      - EMAIL_SUBSCRIPTION=email-subscription
    depends_on:
      - pubsub-emulator
      - web
